# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]      # The name of the module we are confguring is "character"
symbol = "âœ"     # The "symbol" segment is being set to "âœ"

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

[git_branch]
symbol = "îœ¥ "
truncation_length = "4"
truncation_symbol = ""

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[git_state]
progress_divider = " of "
cherry_pick = "ğŸ’ PICKING"

[git_status]
stashed = "ï´– "
modified = "ï‘´ "
staged = "ï˜‘ "
ahead = "ï§„"

[rust]
symbol = "î¨ "
